apiVersion: apps/v1
kind: Deployment
metadata:
  name: parrot
  labels:
    app: parrot
  namespace: default
spec:
  replicas: 3
  selector:
    matchLabels:
      app: parrot
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: parrot
    spec:
      containers:
        - image: dangquanghu/parrot
          imagePullPolicy: Always
          name: parrot
          ports:
            - containerPort: 3000

---
apiVersion: v1
kind: Service
metadata:
  name: parrot
  labels:
    app: parrot
spec:
  type: LoadBalancer
  selector:
    app: parrot
  ports:
    - port: 3000
      targetPort: 8080
      protocol: TCP