version: 2.1

orbs:
  aws-eks: circleci/aws-eks@2.2.0
  kubernetes: circleci/kubernetes@1.3.1

jobs:
  lint:
    docker:
      - image: node:16.3-slim
    steps:
      - checkout

      - run:
          name: Install node_modules
          command: |
            cd website
            npm install

      - run: 
          name: npm lint
          command: |
            cd website
            npm run lint

      - run:
          name: Install hadolint
          command: |
            apt-get update && apt-get install -y wget
            wget -O /bin/hadolint https://github.com/hadolint/hadolint/releases/download/v1.16.3/hadolint-Linux-x86_64 &&\
            chmod +x /bin/hadolint

      - run: 
         name: Dockerfile lint
         command: |
            cd website
            hadolint Dockerfile --ignore  DL3006
  
  build:
    machine: true
    steps:
      - checkout
      - run:
          name: Build and push image
          command: |
            . make.sh blue
            cd website
            docker login -u ${DOCKERHUB_USERNAME} -p ${DOCKERHUB_PASSWORD}
            docker build -t ${DOCKERHUB_USERNAME}/parrot:${TITLE} .
            docker push ${DOCKERHUB_USERNAME}/parrot:${TITLE}
            docker tag ${DOCKERHUB_USERNAME}/parrot:${TITLE} ${DOCKERHUB_USERNAME}/parrot:latest
            docker push ${DOCKERHUB_USERNAME}/parrot:latest
      
  create-cluster:
    parameters:
      custom_checkout:
        type: string
        default: ""
    docker:
      - image: cimg/python:3.7
    steps:
      - when:
          condition: <<parameters.custom_checkout>>
          steps:
            - run: echo "Cluster created"

      - unless:
          condition: <<parameters.custom_checkout>>
          steps:
            - checkout
            - aws-eks/create-cluster:
                cluster-name: udadevops
                node-type: 't3.medium'
                nodes-max: 3
                nodes-min: 2

  create-deployment:
    docker:
      - image: cimg/python:3.7
    steps:
      - checkout
      - kubernetes/install
      - aws-eks/update-kubeconfig-with-authenticator:
          cluster-name: 'udadevops'
          install-kubectl: true
      - kubernetes/create-or-update-resource:
          get-rollout-status: true
          resource-file-path: appdeploy.yml
          resource-name: deployment/parrot
                    
  check-cluster:
    docker:
      - image: cimg/python:3.7
    steps:
      - kubernetes/install
      - aws-eks/update-kubeconfig-with-authenticator:
          cluster-name: 'udadevops'
      - run:
          name: Check cluster
          command: |
            kubectl get svc
            kubectl get nodes
            kubectl get deployment
  
  delete-resource:
    docker:
      - image: cimg/python:3.7
    steps:
      - kubernetes/install
      - aws-eks/update-kubeconfig-with-authenticator:
          cluster-name: 'udadevops'
          install-kubectl: true
      - kubernetes/delete-resource:
                  resource-names: parrot
                  resource-types: deployment
                  wait: true
        
workflows:
  default:
    jobs:
      - lint
      
      - build:
          requires:
            - lint

      # - create-cluster:
      #     custom_checkout: "cluster created"

      - create-cluster:
          requires:
            - build

      - create-deployment:
          requires:
            - create-cluster

      - check-cluster:
          requires:
            - create-deployment

      - aws-eks/update-container-image:
          type: approval
          cluster-name: 'udadevops'
          container-image-updates: parrot=dangquanghui/parrot
          record: true
          resource-name: deployment/parrot

      - check-cluster:
          requires:
            - aws-eks/update-container-image

      - delete-resource:
          type: approval

      - aws-eks/delete-cluster:
          cluster-name: udadevops
          requires:
            - delete-resource