# version: 2.1

# orbs:
#   aws-eks: circleci/aws-eks@2.2.0
#   kubernetes: circleci/kubernetes@1.3.1

# jobs:
#   lint:
#     docker:
#       - image: node:16.3-slim
#     steps:
#       - checkout

#       - run:
#           name: Install node_modules
#           command: |
#             cd website
#             npm install

#       - run: 
#           name: npm lint
#           command: |
#             cd website
#             npm run lint

#       - run:
#           name: Install hadolint
#           command: |
#             apt-get update && apt-get install -y wget
#             wget -O /bin/hadolint https://github.com/hadolint/hadolint/releases/download/v1.16.3/hadolint-Linux-x86_64 &&\
#             chmod +x /bin/hadolint

#       - run: 
#          name: Dockerfile lint
#          command: |
#             cd website
#             hadolint Dockerfile --ignore  DL3006
  
#   build:
#     machine: true
#     steps:
#       - checkout
#       - run:
#           name: Build and push image
#           command: |
#             cd website
#             source .env
#             docker login -u ${DOCKERHUB_USERNAME} -p ${DOCKERHUB_PASSWORD}
#             docker build -t ${DOCKERHUB_USERNAME}/${TITLE} .
#             docker push ${DOCKERHUB_USERNAME}/${TITLE}
#             docker tag ${DOCKERHUB_USERNAME}/${TITLE} ${DOCKERHUB_USERNAME}/parrot:latest
#             docker push ${DOCKERHUB_USERNAME}/parrot:latest

#   check-cluster:
#     docker:
#       - image: amazon/aws-cli
#     steps:
#       - checkout
#       - run: mkdir -p /tmp
#       - run: aws eks describe-cluster --name udadevops > cluster_info.txt
#       - save_cache:
#           paths:
#             - /tmp
#           key: cluster_info-{{ .Environment.CIRCLE_WORKFLOW_ID }}
      
#   create-cluster:
#     executor: aws-eks
#     steps:
#       - checkout
#       - aws-eks/create-cluster:
#           cluster-name: udadevops

      
            
# workflows:
#   default:
#     jobs:
#       # - lint
#       # - build:
#       #     requires:
#       #       - lint
#       - create-master-node
version: 2.1

jobs: # conditional steps may also be defined in `commands:`
  job_with_optional_custom_checkout:
    parameters:
      custom_checkout:
        type: string
        default: ""
    machine:
      image: ubuntu-2004:202107-02
    steps:
      - when:
          condition: <<parameters.custom_checkout>>
          steps:
            - run: echo "my custom checkout"
      - unless:
          condition: <<parameters.custom_checkout>>
          steps:
            - checkout
workflows:
  build-test-deploy:
    jobs:
      - job_with_optional_custom_checkout:
          custom_checkout: "any non-empty string is truthy"
      - job_with_optional_custom_checkout