version: 2.1

orbs:
  aws-eks: circleci/aws-eks@2.2.0
  kubernetes: circleci/kubernetes@1.3.1

jobs:
  lint:
    docker:
      - image: node:16.3-slim
    steps:
      - checkout

      - run:
          name: Install node_modules
          command: |
            cd website
            npm install

      - run: 
          name: npm lint
          command: |
            cd website
            npm run lint

      - run:
          name: Install hadolint
          command: |
            apt-get update && apt-get install -y wget
            wget -O /bin/hadolint https://github.com/hadolint/hadolint/releases/download/v1.16.3/hadolint-Linux-x86_64 &&\
            chmod +x /bin/hadolint

      - run: 
         name: Dockerfile lint
         command: |
            cd website
            hadolint Dockerfile --ignore  DL3006
  
  build:
    machine: true
    steps:
      - checkout
      - run:
          name: Build and push image
          command: |
            . make.sh blue
            cd website
            docker login -u ${DOCKERHUB_USERNAME} -p ${DOCKERHUB_PASSWORD}
            docker build -t ${DOCKERHUB_USERNAME}/${TITLE} .
            docker push ${DOCKERHUB_USERNAME}/parrot:${TITLE}
            docker tag ${DOCKERHUB_USERNAME}/${TITLE} ${DOCKERHUB_USERNAME}/parrot:latest
            docker push ${DOCKERHUB_USERNAME}/parrot:latest

      
  create-cluster:
    parameters:
      custom_checkout:
        type: string
        default: ""
    docker:
      - image: cimg/python:3.7
    steps:
      - when:
          condition: <<parameters.custom_checkout>>
          steps:
            - run: echo "Cluster created"

      - unless:
          condition: <<parameters.custom_checkout>>
          steps:
            - checkout
            - aws-eks/create-cluster:
                cluster-name: udadevops
                node-type: 't3.medium'
                nodes-max: 3
                nodes-min: 2
        
workflows:
  default:
    jobs:
      - lint
      - build:
          requires:
            - lint
      # - create-cluster:
      #     custom_checkout: "cluster created"
      - create-cluster
