Description: >
  Create master node.

Resources:
  InstanceSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupName: !Sub Master-node SG
      GroupDescription: Allow port 22 and port 3030.
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 0.0.0.0/0
  
  EC2Instance:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: t3.medium
      SecurityGroups: 
        - !Ref InstanceSecurityGroup
      KeyName: k8s
      ImageId: ami-0568773882d492fc8
      Tags:
        - Key: Name
          Value: !Sub master
