---

- name: "Test"
  hosts: master
  remote_user: ec2-user
  become_method: sudo
  become_user: root
  gather_facts: false
  vars:
    ansible_python_interpreter: /usr/bin/python3
    ansible_host_key_checking: false
    ansible_stdout_callback: yaml

  pre_tasks:
    - name: "install python for Ansible."
      yum:
        name: python3
        state: latest
        update_cache: yes

  tasks:
    - name: test
      command: echo "Test"
